const REFRESH_MS = 15 * 60 * 1000;
const HISTORY_URL = 'https://lsrezvicwacdqwnkgnzo.supabase.co/rest/v1/medicao_tb';
const HISTORY_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzcmV6dmljd2FjZHF3bmtnbnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ2NTI2MTgsImV4cCI6MjEwMDIyODYxOH0.u-Q6i-2yhM-juIzWYCDvDibgz2uzk9U-4DiaWfAnVM8';
const $ = id => document.getElementById(id);
const setDot = (id, ok) => { const el=$(id); el.className=`dot ${ok?'green':'red'}`; };
const fmt = n => Number(n).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
function clock(){const d=new Date();$('headerDate').textContent=d.toLocaleDateString('pt-BR');$('headerTime').textContent=d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});} clock();setInterval(clock,30000);
function windName(d){return ['N','NE','L','SE','S','SO','O','NO'][Math.round(((Number(d)||0)%360)/45)%8]}
async function loadWeather(){try{const u='https://api.open-meteo.com/v1/forecast?latitude=-29.64357&longitude=-50.80093&current=temperature_2m,apparent_temperature,wind_speed_10m,wind_direction_10m&daily=precipitation_sum&past_days=29&forecast_days=1&timezone=America%2FSao_Paulo';const r=await fetch(u);if(!r.ok)throw 0;const d=await r.json(),c=d.current;$('temperature').textContent=Math.round(c.temperature_2m);$('feelsLike').textContent=Math.round(c.apparent_temperature);$('windSpeed').textContent=fmt(c.wind_speed_10m);$('windDirection').textContent=windName(c.wind_direction_10m);$('windDegrees').textContent=`(${Math.round(c.wind_direction_10m)}°)`;$('rainTotal').textContent=fmt(d.daily.precipitation_sum.reduce((a,b)=>a+(Number(b)||0),0));$('weatherState').textContent='Atualizado';setDot('weatherDot',true)}catch{$('weatherState').textContent='Indisponível';setDot('weatherDot',false)}}
function normalizeHistory(raw){const list=Array.isArray(raw)?raw:(raw?.historico||raw?.data||raw?.leituras||[]);return list.map(x=>({time:new Date(x.time||x.data_hora||x.created_at||x.timestamp||x.data),level:Number(x.level??x.nivel_medicao??x.nivel??x.valor)})).filter(x=>Number.isFinite(x.level)&&!isNaN(x.time)).sort((a,b)=>a.time-b.time).slice(-300)}
async function loadRemoteHistory(){const since=new Date(Date.now()-86400000).toISOString();const url=`${HISTORY_URL}?select=nivel_medicao,created_at&created_at=gte.${encodeURIComponent(since)}&order=created_at.asc&limit=300`;const r=await fetch(url,{headers:{apikey:HISTORY_KEY,Authorization:`Bearer ${HISTORY_KEY}`}});if(!r.ok)throw 0;return normalizeHistory(await r.json())}
async function getJson(paths){for(const path of paths){try{const r=await fetch(`/api/rio-proxy?path=${encodeURIComponent(path)}`);if(r.ok)return await r.json()}catch{}}throw 0}
function situation(level){if(level<2)return['NORMAL','normal'];if(level<3.5)return['ATENÇÃO','attention'];if(level<=4.5)return['ALERTA','alert'];if(level<6)return['ALERTA DE INUNDAÇÃO','emergency'];return['INUNDAÇÃO EXTREMA','emergency']}
function renderChart(points){const w=760,h=250,p={l:42,r:12,t:12,b:30};let grid='';const refs=new Map([[1,'#21a459'],[2,'#e5a10a'],[6,'#202b3c']]);for(let m=0;m<=6;m++){const y=p.t+(6-m)*(h-p.t-p.b)/6;grid+=`<line x1="${p.l}" y1="${y}" x2="${w-p.r}" y2="${y}" stroke="${refs.get(m)||'#dbe8f5'}" stroke-dasharray="5 5"/><text x="4" y="${y+4}" fill="#7486a0" font-size="10">${m},00</text>`}for(const [value,color,label] of [[3.5,'#ee671d','3,50'],[4.5,'#e8313a','4,50']]){const y=p.t+(6-value)*(h-p.t-p.b)/6;grid+=`<line x1="${p.l}" y1="${y}" x2="${w-p.r}" y2="${y}" stroke="${color}" stroke-dasharray="5 5"/><text x="4" y="${y+4}" fill="${color}" font-size="10">${label}</text>`}let line='',markers='';if(points.length){const min=points[0].time,max=points.at(-1).time,range=Math.max(1,max-min),coords=points.map(q=>({x:p.l+(q.time-min)/range*(w-p.l-p.r),y:p.t+(6-Math.max(0,Math.min(6,q.level)))*(h-p.t-p.b)/6}));line=coords.length===1?`M ${p.l} ${coords[0].y} L ${w-p.r} ${coords[0].y}`:coords.map((q,i)=>`${i?'L':'M'} ${q.x} ${q.y}`).join(' ');markers=coords.filter((_,i)=>i===coords.length-1||i%12===0).map(q=>`<circle cx="${q.x}" cy="${q.y}" r="3" fill="#096cdf"/>`).join('')}$('chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">${grid}${line?`<path d="${line}" fill="none" stroke="#096cdf" stroke-width="4" stroke-linejoin="round"/>${markers}`:''}</svg>`}
async function loadRiver(){try{const current=await getJson(['river/level','nivel/atual','nivel']);const value=Number(current.nivelMedicao??current.nivel??current.valor??current.level??current.data?.nivelMedicao??current.data?.nivel);if(!Number.isFinite(value))throw 0;$('riverLevel').textContent=fmt(value);const [name,cls]=situation(value),pill=$('situationPill');pill.className=`pill ${cls}`;pill.innerHTML=`✓ <b>${name}</b><small>Situação do rio</small>`;$('riverUpdated').textContent=new Date(current.data_hora||current.updated_at||current.createdAt||current.created_at||Date.now()).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});$('riverState').textContent='Atualizado';setDot('riverDot',true);$('systemBadge').className='badge online';$('systemBadge').textContent='● OPERACIONAL';let history=[];try{history=await loadRemoteHistory()}catch{}const saved=JSON.parse(localStorage.getItem('rio-v5-history')||'[]').filter(x=>x.time&&Number.isFinite(x.level)&&Date.now()-new Date(x.time).getTime()<86400000);saved.push({time:new Date().toISOString(),level:value});localStorage.setItem('rio-v5-history',JSON.stringify(saved.slice(-300)));if(!history.length)history=normalizeHistory(saved);renderChart(history);$('chartState').textContent=history.length>1?`${history.length} leituras reais`:'Leitura atual';if(history.length>1){const delta=value-history[0].level;$('trend').textContent=`${delta>0?'↑ Subindo':delta<0?'↓ Descendo':'→ Estável'} • ${Math.abs(delta*100).toFixed(0)} cm no período`}}catch{$('riverState').textContent='Indisponível';setDot('riverDot',false);renderChart([])}}
async function refresh(){await Promise.allSettled([loadWeather(),loadRiver()])}refresh();setInterval(refresh,REFRESH_MS);
$('fullscreenButton').addEventListener('click',()=>$('videoStage').requestFullscreen?.());
